In [52]:
import cv2 as cv
import numpy as np

In [53]:
def detect_circles( img , minDist, p1, p2 , min_r , max_r):
    result = img.copy()
    gray = cv.cvtColor(result, cv.COLOR_BGR2GRAY)
    filtered = cv.GaussianBlur(gray, (5, 5), 1)
    # cv.imshow("filtered", filtered)
    circles = cv.HoughCircles(filtered, method=cv.HOUGH_GRADIENT, dp=1, minDist=minDist, 
                            param1=p1, param2=p2, minRadius=min_r, maxRadius=max_r)

    if circles is not None:
        print(circles.shape)
        print(circles)
        circles = np.uint16(np.around(circles))

        for i in circles[0, :]:
            center = (i[0], i[1])
            radius = i[2]
            cv.circle(result, center, radius, (0, 255, 0), 3)
        
    return result
    


In [54]:
img = cv.imread("./circles/brown-eyes.jpg")

result = detect_circles(img, 10, 100, 30, 20, 40)

cv.imshow("Circles", result)
cv.waitKey(0)
cv.destroyAllWindows()

(1, 2, 3)
[[[147.5 126.5  34.9]
  [469.5 126.5  33.8]]]


In [55]:
img = cv.imread("./circles/Ronaldo.jpg")

result = detect_circles(cv.resize(img, (0, 0), fx=0.5, fy=0.5) , 20, 100, 40, 50, 80)

cv.imshow("Ronaldo", result)
cv.waitKey(0)
cv.destroyAllWindows()

(1, 5, 3)
[[[303.5 393.5  69.5]
  [454.5 391.5  71.7]
  [644.5 383.5  69.5]
  [104.5 391.5  69.5]
  [829.5 391.5  71.7]]]
