In [1]:
import cv2 as cv
import numpy as np

In [42]:
img = cv.imread("./circles/brown-eyes.jpg")
img_copy = img.copy()

gray = cv.cvtColor(img_copy, cv.COLOR_BGR2GRAY)
filtered = cv.GaussianBlur(gray, (5, 5), 1)
cv.imshow("filtered", filtered)
circles = cv.HoughCircles(filtered, method=cv.HOUGH_GRADIENT, dp=1, minDist=10, 
                        param1=100, param2=30, minRadius=20, maxRadius=40)

if circles is not None:
    print(circles.shape)
    print(circles)
    circles = np.uint16(np.around(circles))
    print(circles)

    for i in circles[0, :]:
        center = (i[0], i[1])
        radius = i[2]
        cv.circle(img_copy, center, radius, (0, 255, 0), 3)


cv.imshow("Circles", img_copy)
cv.waitKey(0)
cv.destroyAllWindows()

(1, 2, 3)
[[[147.5 126.5  34.9]
  [469.5 126.5  33.8]]]
[[[148 126  35]
  [470 126  34]]]


In [75]:
img = cv.imread("./circles/Ronaldo.jpg")
img_copy = img.copy()
img_copy = cv.resize(img_copy, (0, 0), fx=0.5, fy=0.5)

gray = cv.cvtColor(img_copy, cv.COLOR_BGR2GRAY)
filtered = cv.GaussianBlur(gray, (5, 5), 1)
cv.imshow("filtered", filtered)
circles = cv.HoughCircles(filtered, method=cv.HOUGH_GRADIENT, dp=1, minDist=20, 
                        param1=100, param2=40, minRadius=50, maxRadius=80)

if circles is not None:
    print(circles.shape)
    print(circles)
    circles = np.uint16(np.around(circles))
    print(circles)

    for i in circles[0, :]:
        center = (i[0], i[1])
        radius = i[2]
        cv.circle(img_copy, center, radius, (0, 255, 0), 3)


cv.imshow("Circles", img_copy)
cv.waitKey(0)
cv.destroyAllWindows()

(1, 5, 3)
[[[303.5 393.5  69.5]
  [454.5 391.5  71.7]
  [644.5 383.5  69.5]
  [104.5 391.5  69.5]
  [829.5 391.5  71.7]]]
[[[304 394  70]
  [454 392  72]
  [644 384  70]
  [104 392  70]
  [830 392  72]]]
